name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'

jobs:
  update-pot:
    runs-on: ubuntu-latest
    if: github.repository == "pressbooks/pressbooks-lti-provider"
    steps:
    - uses: actions/checkout@v2
    - name: Update POT file
      uses: pressbooks/action-pressbooks-make-pot@main
      with:
        path: './languages'
        slug: 'pressbooks-lti-provider'
        textdomain: 'pressbooks-lti-provider'
        name: 'Pressbooks LTI Provider'
        headers: "{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-lti-provider/issues\"}"
    - name: Commit updated POT file
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: 'Update languages/pressbooks-lti-provider.pot'
